In [3]:
#import thư viện pandas, os
import pandas as pd
import os

# Đọc thử một file

In [9]:
# Đọc thử 1 file 1 sheet
df_data = pd.read_excel('BANG CONG T10-2022 AN HA.xlsx',sheet_name="XUONG AH3", skiprows=9,usecols="C,D,BQ,BR")

In [5]:
df_data

                  2             3      68    69
0       ĐÀM VĂN TUẤN  Tổ Ráp Thô 1  196.0  62.5
1         VÕ TẤN HẬU  Tổ Ráp Thô 1  208.0  66.0
2         DANH HOÀNH  Tổ Ráp Thô 1  208.0  77.5
3     NGUYỄN TẤN LỢI  Tổ Ráp Thô 1  204.0  56.5
4      LÊ THÀNH TÍCH  Tổ Ráp Thô 1  186.0  50.0
..               ...           ...    ...   ...
188              NaN           NaN    NaN   NaN
189              NaN           NaN    NaN   NaN
190              NaN           NaN    NaN   NaN
191              NaN           NaN    NaN   NaN
192  NGUYỄN VĂN ĐỊNH           NaN    NaN   NaN

[193 rows x 4 columns]

In [10]:
# drop giá trị NaN
df_data=df_data.dropna(axis=0)
# đổi tên 
df_data.columns=["Họ và tên","Bộ phận","HC","TC"]
# tạo cột ngày
df_data["Ngày tháng"] = "Tháng10/2023"
# Tạo cột tổng giờ
df_data["Tổng giờ"] = df_data["HC"] + df_data["TC"]

In [11]:
df_data

          Họ và tên       Bộ phận     HC    TC    Ngày tháng  Tổng giờ
0      ĐÀM VĂN TUẤN  Tổ Ráp Thô 1  196.0  62.5  Tháng10/2023     258.5
1        VÕ TẤN HẬU  Tổ Ráp Thô 1  208.0  66.0  Tháng10/2023     274.0
2        DANH HOÀNH  Tổ Ráp Thô 1  208.0  77.5  Tháng10/2023     285.5
3    NGUYỄN TẤN LỢI  Tổ Ráp Thô 1  204.0  56.5  Tháng10/2023     260.5
4     LÊ THÀNH TÍCH  Tổ Ráp Thô 1  186.0  50.0  Tháng10/2023     236.0
..              ...           ...    ...   ...           ...       ...
175       LÊ VĂN VŨ   Tổ Đóng gói  204.0  86.0  Tháng10/2023     290.0
176     VÕ VĂN DŨNG   Tổ Đóng gói  192.0  46.0  Tháng10/2023     238.0
177    HÀ HẢI DƯƠNG   Tổ Đóng gói  204.0  66.0  Tháng10/2023     270.0
178  LÊ THANH TUYỀN   Tổ Đóng gói  208.0  62.5  Tháng10/2023     270.5
179      LÊ ĐẠI HỌC   Tổ Đóng gói  208.0  90.0  Tháng10/2023     298.0

[156 rows x 6 columns]

# Viết hàm tự động chạy các sheet

In [132]:
# Tạo 1 list danh sách các sheet 
sheet_name=["XUONG AH1","XUONG AH2","XUONG AH3"]

In [138]:
# Tạo một hàm đọc các sheet cho 1 file
total=[]
for i in sheet_name:
    df_data=pd.read_excel('BANG CONG T10-2022 AN HA.xlsx',sheet_name=i,skiprows=9,usecols="C,D,BQ,BR")
    df_data.columns=["Họ và tên","Bộ phận","HC","TC"]
    df_data["Ngày tháng"] = "Tháng10/2023"
    df_data["Xưởng"] = i
    df_data=df_data.dropna(axis=0)
    total.append(df_data)
    resultt=pd.concat(total)

In [139]:
resultt

            Họ và tên      Bộ phận     HC     TC    Ngày tháng      Xưởng
0    TRỊNH VĂN THÀNH    Tổ Cắt CNC  208.0  108.5  Tháng10/2023  XUONG AH1
1        LÊ ĐÌNH THẢO   Tổ Cắt CNC  197.0  131.5  Tháng10/2023  XUONG AH1
2      TRẦN VĂN THẮNG   Tổ Cắt CNC  163.5   78.0  Tháng10/2023  XUONG AH1
3     NGUYỄN DUY TÙNG   Tổ Cắt CNC  173.0   91.0  Tháng10/2023  XUONG AH1
4       ĐOÀN VĂN THỪA   Tổ Cắt CNC  188.0  124.0  Tháng10/2023  XUONG AH1
..                ...          ...    ...    ...           ...        ...
175         LÊ VĂN VŨ  Tổ Đóng gói  204.0   86.0  Tháng10/2023  XUONG AH3
176       VÕ VĂN DŨNG  Tổ Đóng gói  192.0   46.0  Tháng10/2023  XUONG AH3
177      HÀ HẢI DƯƠNG  Tổ Đóng gói  204.0   66.0  Tháng10/2023  XUONG AH3
178    LÊ THANH TUYỀN  Tổ Đóng gói  208.0   62.5  Tháng10/2023  XUONG AH3
179        LÊ ĐẠI HỌC  Tổ Đóng gói  208.0   90.0  Tháng10/2023  XUONG AH3

[358 rows x 6 columns]

# Viết hàm chạy tự động chạy các file

In [13]:
# tạo đường dẫn đến thư mục chứa
path="C:/Users/Admin/Desktop/BANG CONG/BANG CONG/AN HA/"

In [14]:
# sử dụng listdir duyệt qua các file trong thư mục đường dẫn path
os.listdir(path)

['BANG CONG T01-2023.xlsx',
 'BANG CONG T02-2023.xlsx',
 'BANG CONG T03-2023.xlsx',
 'BANG CONG T04-2023.xlsx',
 'BANG CONG T05-2023.xlsx',
 'BANG CONG T10-2022 AN HA.xlsx',
 'BANG CONG T11-2022.xlsx',
 'BANG CONG T12-2022.xlsx']

In [ ]:
sheet_name=["XUONG AH1","XUONG AH2","XUONG AH3"]

In [164]:
# Tạo hàm
frames=[]
for i in os.listdir(path):
    if i.endswith(".xlsx"):
        filepath = path + i
        for f in sheet_name:
            df1=pd.read_excel(filepath,sheet_name=f, skiprows=9,usecols="C,D,BQ,BR")
            df1.columns=["Họ và tên","Bộ phận","HC","TC"]
            df1["Tổng giờ"] = df1["HC"] + df1["TC"]
            df1["Xưởng"] = f[5:]
            df1["Ngày tháng"] = i[9:18]
            df1=df1.dropna(axis=0)
            frames.append(df1)
            result = pd.concat(frames)

In [165]:
result

            Họ và tên      Bộ phận     HC     TC  Tổng giờ Xưởng Ngày tháng
0    TRỊNH VĂN THÀNH    Tổ Cắt CNC  128.0   68.0     196.0   AH1   T01-2023
1        LÊ ĐÌNH THẢO   Tổ Cắt CNC  128.0   98.0     226.0   AH1   T01-2023
2      TRẦN VĂN THẮNG   Tổ Cắt CNC  140.0   52.0     192.0   AH1   T01-2023
3     NGUYỄN DUY TÙNG   Tổ Cắt CNC  112.0   65.0     177.0   AH1   T01-2023
4       ĐOÀN VĂN THỪA   Tổ Cắt CNC  124.0   96.0     220.0   AH1   T01-2023
..                ...          ...    ...    ...       ...   ...        ...
164         LÊ VĂN VŨ  Tổ Đóng gói  196.0  128.5     324.5   AH3   T12-2022
165       VÕ VĂN DŨNG  Tổ Đóng gói  170.0   82.0     252.0   AH3   T12-2022
166      HÀ HẢI DƯƠNG  Tổ Đóng gói  192.0   93.0     285.0   AH3   T12-2022
167    LÊ THANH TUYỀN  Tổ Đóng gói  200.0  120.0     320.0   AH3   T12-2022
168        LÊ ĐẠI HỌC  Tổ Đóng gói  176.0  102.5     278.5   AH3   T12-2022

[3346 rows x 7 columns]

In [167]:
# Lưu file vào 1 file excel
result.to_excel("TH.xlsx")